version: '3'

services:
  # ganachecli: simulated test rpc on dev environment
  ganache-cli:
    container_name: ganache-cli
    build:
      context: ./ganache
    ports:
      - 8545:8545

  # truffle-suite
  # volumes are used here to enable hot editing :) Nice trick!
  truffle:
    container_name: truffle
    build:
      context: truffle
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' localhost:8545
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      sh -c "truffle compile &&
             truffle test &&
             truffle migrate &&
             cp -R output/contracts app/src/contracts/ &&
             cd app &&
             npm start"
    ports:
      - 3000:3000
    tty: true
    # added volumes for contracts, migtrations and tests / removed COPY operations in Dockerfile
    #- ./truffledrizzle/client/node_modules:/client/node_modules
    volumes:
      #- ./truffledrizzle/client:/client. => DOES NOT WORK !!!1
      - ./truffle/app/src:/app/src
      - ./truffle/app/public:/app/public
      - ./truffle/contracts:/contracts
      - ./truffle/migrations:/migrations
      - ./truffle/test:/test
